# Generated by Django 6.0.5 on 2026-05-19 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_prescription_prescriptionitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionitem',
            name='custom_medicine_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='prescriptionitem',
            name='medicine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.medicine'),
        ),
    ]
