# Generated by Django 6.0.5 on 2026-05-19 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_prescriptionitem_custom_medicine_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriptionitem',
            name='medicine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.medicine'),
        ),
    ]
