# Generated by Django 6.0.5 on 2026-05-19 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_prescriptionitem_medicine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescriptionitem',
            name='prescriction',
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='prescription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.prescription'),
        ),
    ]
