# Generated by Django 6.0.5 on 2026-05-19 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fee',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
